apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-depl
spec:
  replicas: 1
  # this tells deployment, how to find all the pods it has to create
  selector:
    matchLabels:
      app: payments

  # how to create each individual pod that this deployment is going to create
  template:
    metadata:
      # selector has to match the label
      labels:
        app: payments

    spec:
      containers:
        - name: payments
          image: kalinicovic/payments
          env:
            # this service handles authentication by itself. it will validate the token if it has the original key.
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  # we create this by "kubectl create secret generic jwt-secret --from-literal=JWT_KEY=randomkey"
                  name: jwt-secret
                  key: JWT_KEY
            - name: STRIPE_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-secret
                  key: STRIPE_KEY
            - name: MONGO_URI
              value: "mongodb://payments-mongo-srv:27017/payments"
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: NATS_CLIENT_ID
              # we are assigning pod name as unique client id
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

---
apiVersion: v1
kind: Service
metadata:
  name: payments-srv
spec:
  # this tells the service how to find the set of pods that is supposed to govern access to. we want to find all the pods app:payments
  selector:
    app: payments
  ports:
    - name: payments
      protocol: TCP
      port: 3000
      targetPort: 3000
