name: deploy-expiration

# on dictates when this should be executed
on:
  #   merge and pull request counted as push directly to master branch
  push:
    branches:
      - master
    paths:
      - "expiration/**"
jobs:
  build:
    #    docker already installed on this container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd expiration && docker build -t kalinicovic/expiration .
      #       to push the image to docker we must be logged in docker cli.
      #  we have to somehow tell docker to login. we enter username and password as secret
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push kalinicovic/expiration
      - uses: digitalocean/action-doctl@v2
        with:
          #          token will be provided to 'digitalocean/action-doctl@v2' script and we are going to get
          # preinitialized version of doctl.
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save ticketing
      - run: kubectl rollout restart deployment expiration-depl
